"""
STAR File Z-Cut Classifier.

This module processes a STAR file generated by CLIC (Cryo-EM clustering tool)
to extract particle classifications based on a user-defined Z-cut threshold.

It identifies the iteration index where the Z-cut applies, then extracts
corresponding class labels and image paths from the STAR file.

Usage:
    python classify_particles.py -i particles.star -c 0.35

Args:
    -i / --input : Path to the STAR file.
    -c / --cut   : Z-cut threshold value.

Dependencies:
    - argparse
    - gemmi
"""

import argparse
from typing import List, Tuple

import gemmi


def from_z(z_row: List[str], z_cut: float) -> int:
    """
    Determines the iteration index at which the Z-cut threshold separates classes.

    Args:
        z_row: List of Z values from the STAR file.
        z_cut: Threshold value to determine the cut point.

    Returns:
        Index of the iteration just below the Z-cut threshold.
        If the threshold is too high, returns the length of z_row.
    """
    for x, z in enumerate(z_row):
        if z_cut < float(z):
            return x - 1
    print("ERROR: Cut too high, all in one class")
    return len(z_row)


def cut(star_file: str, z_cut: float) -> Tuple[List[int], List[str], List[str]]:
    """
    Parses the STAR file and extracts particle classifications based on Z-cut.

    Args:
        star_file: Path to the STAR file generated by CLIC.
        z_cut: Z-cut threshold to determine classification level.

    Returns:
        A tuple containing:
            - classes: Particle class assignments.
            - im_names: Corresponding image file names.
            - vals: Raw classification values from the selected iteration.
    """
    dendro_star = gemmi.cif.read_file(star_file)
    block = dendro_star.find_block('particles')
    for x in block:
        table = x.loop
    tags = table.tags
    table = block.find(tags)
    z_row = list(table[0])[2:]
    it = from_z(z_row, z_cut)
    im_names = [x for x in block.find_values('_path')][1:]
    vals = list(block.find_values(f'_it{it}'))[1:]
    classes = [int(x) for x in vals]

    return classes, im_names, vals


if __name__ == '__main__':
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "-i", "--input",
        help="STAR file from CLIC",
        required=True,
        type=str
    )
    parser.add_argument(
        "-c", "--cut",
        help="Level to cut at",
        required=True,
        type=float
    )

    args = parser.parse_args()

    cut(args.input, args.cut)
